### ISSUE TITLE
k8s security

### ISSUE THREAD

**Issue by klauserber** [workshops-de/cloudnative-workshop#4]
Dem neuen Kurs fehlen noch die Inhalte zum Thema Security.
 
In der Kursbeschreibung haben wir dazu diese Themen:

Certificates Signing
Authorization
Network Policies

Zu Not kann man natürlich noch die alten Folien und Übungen herausholen, aber eine Runderneuerung wäre natürlich schöner.

**Comment by wahler** [comment]
Ich fand die Übung mit der Zertifikatsgenerierung nicht so ideal. Hatte das Gefühl die Teilnehmer komplett abzuhängen. Es wurde gefühlt nur Copy & Paste ohne Verständnis betrieben. 
Folien dazu können wir gerne wieder mit aufnehmen

**Comment by wahler** [comment]
Erledigt
